import { useEffect, useMemo, useRef, useState } from "react";

// 使用 Vite 的站点根路径：本地预览、GitHub Pages 子目录和日后自定义域名都能找到同一份 assets。
const ASSET = (folder, file) => encodeURI(`${import.meta.env.BASE_URL}assets/${folder}/${file}`);
const CORE = "第一批_核心素材";
const DECOR = "第二批_装饰与功能素材";
const DOODLE = `${DECOR}/doodles`;
const people = [{ id: "lin", name: "林晓", color: "pink", key: "key-pink 1.png" }, { id: "chen", name: "陈默", color: "blue", key: "key-blue 1.png" }, { id: "zhou", name: "周屿", color: "green", key: "key-green 1.png" }];
const photos = [{ id: "apartment", label: "客厅合照", src: ASSET(DECOR, "photo-apartment.webp") }, { id: "city", label: "城市黄昏", src: ASSET(DECOR, "photo-city.webp") }, { id: "cat", label: "小猫来访", src: ASSET(DECOR, "photo-cat.webp") }];
const initialLayout = [
  { id: "header", x: 31.5, y: 4.2, w: 36.5, h: 23.2, r: 0, kind: "paper" }, { id: "photo-left", x: 5.5, y: 2, w: 20, h: 30, r: 6, kind: "photo" }, { id: "photo-right", x: 66, y: 2.2, w: 17.5, h: 26.25, r: -5, kind: "photo" }, { id: "keys", x: 84, y: 4, w: 13.4, h: 35.5, r: 0, kind: "keys" },
  { id: "aa", x: 4.7, y: 31.2, w: 29.4, h: 30.5, r: 0, kind: "paper" }, { id: "today", x: 35.3, y: 35.5, w: 27.7, h: 52, r: 0, kind: "paper" }, { id: "chores", x: 63.5, y: 31.2, w: 25.6, h: 30.5, r: 1, kind: "paper" }, { id: "supplies", x: 4.7, y: 62.8, w: 29.4, h: 31.5, r: -1, kind: "paper" }, { id: "rules", x: 63.5, y: 62.8, w: 25.6, h: 31.5, r: -1, kind: "paper" }, { id: "quick", x: 89.6, y: 40.5, w: 8.1, h: 47.5, r: 0, kind: "quick" },
  { id: "plant", x: 1.4, y: 74, w: 8.5, h: 13, r: -5, asset: ASSET(DECOR, "decor-potted-plant.png"), kind: "decor" }, { id: "heart-doodle", x: 27, y: 25, w: 5, h: 5, r: -9, asset: ASSET(`${DOODLE}/black`, "heart.png"), kind: "decor" }, { id: "star-doodle", x: 57, y: 8, w: 4.4, h: 4.4, r: 8, asset: ASSET(`${DOODLE}/black`, "star.png"), kind: "decor" },
];
const modules = { aa: { title: "AA 费用", icon: "icon-coins.png", tone: "paper-lined", detail: "把共同支出摊清楚，今天少一点尴尬。" }, chores: { title: "清洁值日", icon: "icon-broom.png", tone: "paper-grid", detail: "轮到谁、做什么、有没有完成，一眼就知道。" }, supplies: { title: "公共物品", icon: "icon-cart.png", tone: "paper-white", detail: "用完之前提醒，下一次采购不用再问一遍。" }, rules: { title: "室友公约", icon: "icon-document.png", tone: "paper-cream", detail: "把共同认可的生活规则，放在大家都看得到的地方。" } };
const fastenerTargets = new Set(["aa", "today", "chores", "supplies", "rules"]);
const defaultFastener = (id) => (id === "aa" || id === "chores" ? "blue" : id === "today" ? "red" : "pink");
const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

function DraggableItem({ item, editMode, selected, boardRef, onSelect, onMove, onClick, layer = "paper", children }) {
  const dragRef = useRef(null);
  const down = (event) => { if (!editMode) return; event.stopPropagation(); const rect = boardRef.current?.getBoundingClientRect(); if (!rect) return; event.currentTarget.setPointerCapture?.(event.pointerId); onSelect(item.id); dragRef.current = { startX: event.clientX, startY: event.clientY, rect, item }; };
  const move = (event) => { if (!dragRef.current) return; const { startX, startY, rect, item: start } = dragRef.current; onMove(item.id, { x: clamp(start.x + ((event.clientX - startX) / rect.width) * 100, 0, 100 - start.w), y: clamp(start.y + ((event.clientY - startY) / rect.height) * 100, 0, 100 - start.h) }); };
  return <div className={`board-item layer-${layer} ${selected ? "is-selected" : ""} ${editMode ? "is-editable" : ""}`} style={{ left: `${item.x}%`, top: `${item.y}%`, width: `${item.w}%`, height: `${item.h}%`, transform: `rotate(${item.r || 0}deg)` }} onPointerDown={down} onPointerMove={move} onPointerUp={() => { dragRef.current = null; }} onPointerCancel={() => { dragRef.current = null; }} onClick={(event) => { event.stopPropagation(); onClick?.(item.id); }}>{children}</div>;
}
function Pin({ color = "blue", type = "pin" }) { const file = type === "paperclip" ? "paperclip.png" : type === "binder" ? "binder-clip.png" : `pin-${color}.png`; return <img className={`pin pin-${type}`} src={ASSET(DECOR, file)} alt="" />; }
function Fastener({ item, fallback }) { const type = item?.fastener || `pin-${fallback}`; if (type === "paperclip") return <Pin type="paperclip" />; if (type === "binder") return <Pin type="binder" />; return <Pin color={type.replace("pin-", "")} />; }
function FastenerOverlay({ item }) { return <div className={`fastener-overlay fastener-${item.id}`} style={{ left: `${item.x}%`, top: `${item.y}%`, width: `${item.w}%`, height: `${item.h}%`, transform: `rotate(${item.r || 0}deg)` }}><Fastener item={item} fallback={defaultFastener(item.id)} /></div>; }

function ModulePaper({ moduleId, stockReady = false }) {
  const module = modules[moduleId];
  const paperFiles = { "paper-lined": "paper-looseleaf-lined 1.png", "paper-grid": "paper-notebook-grid.png", "paper-white": "paper-white-torn.png", "paper-cream": "paper-cream-aged.png" };
  return <div className={`module-paper ${module.tone}`} style={{ backgroundImage: `url("${ASSET(CORE, paperFiles[module.tone])}")` }}><div className={`module-safe module-safe-${moduleId}`}><div className="paper-heading"><img src={ASSET(DECOR, module.icon)} alt="" /><h2>{module.title}</h2></div>
    {moduleId === "aa" && <div className="paper-content aa-content"><div className="data-row"><span>本月共同支出</span><strong>¥1,286.50</strong></div><div className="data-row highlight-row"><span>我的待补款</span><strong>¥86.40</strong></div><div className="data-row"><span>最近一笔　电费</span><strong>¥268.00</strong></div></div>}
    {moduleId === "chores" && <div className="paper-content chores-content"><div className="tag-line"><span>今日任务</span><b>清理厨房</b></div><div className="data-row"><span>负责人</span><strong className="name-tag blue-tag">林晓</strong></div><div className="next-task">下一个任务：周二 · 陈默 · 倒垃圾</div></div>}
    {moduleId === "supplies" && <div className="paper-content supplies-content"><div className="data-row"><span>快用完</span><strong className={stockReady ? "blue-tag" : "pink-tag"}>{stockReady ? "已补货" : "卫生纸"}</strong></div><div className="data-row"><span>{stockReady ? "库存状态" : "已用完"}</span><strong className={stockReady ? "blue-tag" : "pink-tag"}>{stockReady ? "充足" : "垃圾袋"}</strong></div><div className="data-row"><span>待购买</span><strong className="blue-tag number-tag">{stockReady ? "0 件" : "2 件"}</strong></div><div className="last-update">最近更新：{stockReady ? "你 · 刚刚" : "周屿 · 昨晚"}</div></div>}
    {moduleId === "rules" && <div className="paper-content rules-content"><div className="data-row rule-row"><span>最新规则</span><strong className="pink-tag">留宿需提前说明</strong></div><div className="data-row"><span>更新时间</span><strong>9 月 11 日</strong></div><div className="data-row"><span>确认进度</span><strong className="blue-tag number-tag">2 / 3 人已确认</strong></div><div className="data-row"><span>当前用户状态</span><strong className="pink-tag">待确认</strong></div></div>}
  </div></div>;
}
function Polaroid({ photo, editing }) { return <div className={`polaroid ${editing ? "is-editing" : ""}`}><div className="polaroid-card"><img className="polaroid-photo" src={photo.src} alt={photo.label} /><img className="polaroid-frame" src={ASSET(CORE, "polaroid-frame-v2.png")} alt="" />{!editing && <span className="polaroid-hint">点击查看照片</span>}</div></div>; }
function HeaderNote() { return <div className="header-note" style={{ backgroundImage: `url("${ASSET(CORE, "paper-white-torn.png")}")` }}><div className="tape tape-pink" style={{ backgroundImage: `url("${ASSET(DECOR, "tape-pink.png")}")` }} /><div className="header-brand">Roomie</div><div className="header-home">梧桐公寓 · 302</div><div className="header-date">2026 年 9 月 14 日 · 周一</div></div>; }
function KeyChain({ frontKey, onKeyFront }) { return <div className="key-chain" aria-label="室友钥匙"><img className="key-hook" src={ASSET(CORE, "key-hook-ring 1.png")} alt="" /><div className="key-list">{people.map((person, index) => <div className={`key-entry key-${person.color} ${frontKey === person.id ? "is-front" : ""}`} style={{ zIndex: frontKey === person.id ? 10 : 3 - index }} key={person.id}><img src={ASSET(CORE, person.key)} alt="" /><button className="key-hit" onClick={(event) => { event.stopPropagation(); onKeyFront(person.id); }} aria-label={`把${person.name}的钥匙放到最前`}><span>{person.name}</span></button></div>)}</div></div>; }
function QuickActions({ onAction }) { return <div className="quick-actions"><div className="quick-heading">快捷操作</div><button className="quick-button pink" onClick={(event) => { event.stopPropagation(); onAction("expense"); }}><img src={ASSET(DECOR, "icon-coins.png")} alt="" />记一笔费用</button><button className="quick-button blue" onClick={(event) => { event.stopPropagation(); onAction("chore"); }}><img src={ASSET(DECOR, "icon-broom.png")} alt="" />完成值日</button><button className="quick-button green" onClick={(event) => { event.stopPropagation(); onAction("stock"); }}><img src={ASSET(DECOR, "icon-cart.png")} alt="" />补充库存</button><button className="quick-button purple" onClick={(event) => { event.stopPropagation(); onAction("rule"); }}><img src={ASSET(DECOR, "icon-document.png")} alt="" />查看公约</button></div>; }
function TodayNote({ done }) { const tasks = [{ id: "expense", text: "向陈默补款", meta: "¥86.40" }, { id: "chore", text: "今天由林晓清理厨房" }, { id: "stock", text: "卫生纸和垃圾袋需要补货" }]; return <div className="today-note" style={{ backgroundImage: `url("${ASSET(CORE, "paper-note-yellow 1.png")}")` }}><div className="today-heading"><span>今天有</span><strong>3</strong><span>件事</span></div><div className="today-list">{tasks.map((task) => <div className={`today-task ${done[task.id] ? "is-done" : ""}`} key={task.id}><span className="task-checkbox">{done[task.id] ? "✓" : ""}</span><span>{task.text}</span>{task.meta && <b>{task.meta}</b>}</div>)}</div><div className="smile-mark">☺</div></div>; }

function PhotoViewer({ items, activeId, onClose, onSelect }) { const startX = useRef(null); const index = items.findIndex((item) => item.id === activeId); if (index < 0) return null; const ordered = [items[index], ...items.filter((item) => item.id !== activeId)]; const move = (delta) => onSelect(items[(index + delta + items.length) % items.length].id); return <div className="photo-viewer-backdrop" onClick={onClose}><section className="photo-viewer" onClick={(event) => event.stopPropagation()} onPointerDown={(event) => { startX.current = event.clientX; }} onPointerUp={(event) => { if (startX.current === null) return; const distance = event.clientX - startX.current; if (Math.abs(distance) > 46) move(distance < 0 ? 1 : -1); startX.current = null; }}><button className="viewer-close" onClick={onClose}>关闭</button><div className="viewer-title">我们住在一起的片段</div><div className="photo-stack">{ordered.slice(0, 4).reverse().map((item, stackIndex) => <div className={`viewer-card ${item.id === activeId ? "is-active" : ""}`} style={{ transform: item.id === activeId ? "rotate(-2deg) translateY(-6px)" : `rotate(${(stackIndex - 1) * 6}deg) translate(${(stackIndex - 1) * 12}px, ${stackIndex * 5}px)` }} key={item.id}><Polaroid photo={item.photo} editing /></div>)}</div><div className="viewer-controls"><button onClick={() => move(-1)}>← 上一张</button><span>{index + 1} / {items.length}</span><button onClick={() => move(1)}>下一张 →</button></div><p>左右拖动也能查看，当前照片在最上方。</p></section></div>; }

function Modal({ moduleId, onClose, onAction, expenses }) { if (!moduleId) return null; const module = moduleId === "today" ? { title: "今天要处理", detail: "把今天的三件小事，一件一件完成。", icon: "icon-document.png" } : modules[moduleId]; return <div className="modal-backdrop" onClick={onClose}><section className="detail-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>关闭</button><div className="modal-topline"><img src={ASSET(DECOR, module.icon)} alt="" /><div><div className="modal-eyebrow">ROOMIE · 梧桐公寓 302</div><h2>{module.title}</h2></div></div><p className="modal-detail">{module.detail}</p>{moduleId === "today" && <div className="modal-list"><div><span className="modal-dot pink-dot" />向陈默补款 <b>¥86.40</b><button onClick={() => onAction("expense")}>去处理</button></div><div><span className="modal-dot blue-dot" />林晓 · 清理厨房 <button onClick={() => onAction("chore")}>标记完成</button></div><div><span className="modal-dot green-dot" />卫生纸和垃圾袋补货 <button onClick={() => onAction("stock")}>更新库存</button></div></div>}{moduleId === "aa" && <div className="modal-list"><div className="modal-stat"><span>本月共同支出</span><strong>¥1,286.50</strong></div><div className="modal-stat"><span>我的待补款</span><strong className="pink-number">¥86.40</strong></div><div className="modal-note">最近一笔：电费 · ¥268.00 · 林晓先付</div><button className="modal-primary" onClick={() => onAction("expense")}>新增一笔费用</button></div>}{moduleId === "chores" && <div className="modal-list"><div className="modal-stat"><span>今天</span><strong>林晓 · 清理厨房</strong></div><div className="modal-stat"><span>周二</span><strong>陈默 · 倒垃圾</strong></div><button className="modal-primary" onClick={() => onAction("chore")}>标记今天已完成</button></div>}{moduleId === "supplies" && <div className="modal-list"><div className="modal-stat"><span>快用完</span><strong>卫生纸</strong></div><div className="modal-stat"><span>已用完</span><strong>垃圾袋</strong></div><div className="modal-note">待购买 2 件 · 最近更新：周屿 · 昨晚</div><button className="modal-primary" onClick={() => onAction("stock")}>标记已补货</button></div>}{moduleId === "rules" && <div className="modal-list"><div className="modal-stat"><span>最新规则</span><strong>访客留宿请提前说明</strong></div><div className="modal-stat"><span>确认进度</span><strong>2 / 3 人已确认</strong></div><button className="modal-primary" onClick={() => onAction("rule")}>确认我已阅读</button></div>}{expenses.length > 0 && moduleId === "aa" && <div className="expense-history">本次演示新增：{expenses[expenses.length - 1].name} · ¥{expenses[expenses.length - 1].amount}</div>}</section></div>; }
function ExpenseForm({ onSubmit, onCancel }) { const [name, setName] = useState("周末公共采购"); const [amount, setAmount] = useState("128"); return <div className="modal-backdrop" onClick={onCancel}><section className="expense-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onCancel}>取消</button><div className="modal-eyebrow">记录一笔共同支出</div><h2>把这笔费用放上公告板</h2><label>费用名称<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>金额<input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><button className="modal-primary" onClick={() => onSubmit({ name, amount: Number(amount || 0).toFixed(2) })}>保存费用</button></section></div>; }
function MaterialTray({ selectedItem, onAdd, onFastener, onPhotoPick, onDelete, onClose, onReset }) { const doodles = [["heart", ASSET(`${DOODLE}/pink`, "heart.png")], ["star", ASSET(`${DOODLE}/black`, "star.png")], ["arrow", ASSET(`${DOODLE}/blue`, "arrow.png")], ["sparkle", ASSET(`${DOODLE}/blue`, "sparkle.png")]]; return <div className="material-tray"><div className="tray-head"><div><span className="tray-kicker">EDIT MODE</span><strong>装饰你的公告板</strong></div><div className="tray-actions"><button onClick={onReset}>恢复默认布局</button><button className="tray-cancel" onClick={onClose}>完成编辑</button></div></div><div className="tray-columns"><div className="tray-group"><span className="tray-label">图钉与夹子</span><div className="material-row pin-row"><button aria-label="红色图钉" onClick={() => onFastener("pin-red")}><Pin color="red" /></button><button aria-label="蓝色图钉" onClick={() => onFastener("pin-blue")}><Pin color="blue" /></button><button aria-label="粉色图钉" onClick={() => onFastener("pin-pink")}><Pin color="pink" /></button><button aria-label="曲别针" onClick={() => onFastener("paperclip")}><Pin type="paperclip" /></button><button aria-label="长尾夹" onClick={() => onFastener("binder")}><Pin type="binder" /></button></div></div><div className="tray-group"><span className="tray-label">涂鸦贴纸</span><div className="material-row doodle-row">{doodles.map(([name, src]) => <button key={name} onClick={() => onAdd({ name, asset: src })}><img src={src} alt={name} /></button>)}</div></div><div className="tray-group"><span className="tray-label">拍立得照片</span><div className="material-row photo-row">{photos.map((photo) => <button key={photo.id} onClick={() => onPhotoPick(photo)}><img src={photo.src} alt={photo.label} /></button>)}</div></div><div className="tray-group tray-delete"><span className="tray-label">当前选中</span><div className="selected-name">{selectedItem?.id || "点击纸片或拍立得"}</div><button onClick={onDelete} disabled={!selectedItem || selectedItem.kind !== "decor"}>删除装饰</button></div></div><p className="tray-tip">选中拍立得后可替换它的照片；未选中拍立得时会新增一张。贴纸会覆盖纸片与照片，但始终在图钉、夹子和钥匙下方。</p></div>; }

export function App() {
  const boardRef = useRef(null); const [layout, setLayout] = useState(() => { try { return JSON.parse(localStorage.getItem("roomie-layout-v9")) || initialLayout; } catch { return initialLayout; } }); const [editMode, setEditMode] = useState(false); const [selectedId, setSelectedId] = useState(null); const [frontKey, setFrontKey] = useState("chen"); const [activeModule, setActiveModule] = useState(null); const [photoViewerId, setPhotoViewerId] = useState(null); const [expenseForm, setExpenseForm] = useState(false); const [expenses, setExpenses] = useState(() => { try { return JSON.parse(localStorage.getItem("roomie-expenses-v1")) || []; } catch { return []; } }); const [done, setDone] = useState(() => { try { return JSON.parse(localStorage.getItem("roomie-done-v1")) || {}; } catch { return {}; } }); const [stockReady, setStockReady] = useState(false); const [toast, setToast] = useState("");
  const selectedItem = useMemo(() => layout.find((item) => item.id === selectedId), [layout, selectedId]); const getItem = (id) => layout.find((item) => item.id === id) || initialLayout.find((item) => item.id === id); const photoForItem = (item, fallback) => item?.photoAsset ? { src: item.photoAsset, label: item.photoLabel || fallback.label } : fallback;
  const boardPolaroids = useMemo(() => [{ id: "photo-left", photo: photoForItem(layout.find((item) => item.id === "photo-left"), photos[0]) }, { id: "photo-right", photo: photoForItem(layout.find((item) => item.id === "photo-right"), photos[1]) }, ...layout.filter((item) => item.kind === "decor" && item.photo).map((item) => ({ id: item.id, photo: { src: item.asset, label: item.photoLabel || "拍立得" } }))], [layout]);
  useEffect(() => { localStorage.setItem("roomie-layout-v9", JSON.stringify(layout)); }, [layout]); useEffect(() => { localStorage.setItem("roomie-expenses-v1", JSON.stringify(expenses)); }, [expenses]); useEffect(() => { localStorage.setItem("roomie-done-v1", JSON.stringify(done)); }, [done]); useEffect(() => { if (!toast) return undefined; const timer = setTimeout(() => setToast(""), 2200); return () => clearTimeout(timer); }, [toast]); useEffect(() => { if (!photoViewerId) return undefined; const handleKey = (event) => { const index = boardPolaroids.findIndex((item) => item.id === photoViewerId); if (event.key === "Escape") setPhotoViewerId(null); if (event.key === "ArrowLeft") setPhotoViewerId(boardPolaroids[(index - 1 + boardPolaroids.length) % boardPolaroids.length]?.id); if (event.key === "ArrowRight") setPhotoViewerId(boardPolaroids[(index + 1) % boardPolaroids.length]?.id); }; window.addEventListener("keydown", handleKey); return () => window.removeEventListener("keydown", handleKey); }, [photoViewerId, boardPolaroids]);
  const updateItem = (id, patch) => setLayout((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item)); const notify = (message) => setToast(message); const completeTask = (action) => { if (action === "stock") { setStockReady(true); notify("库存已更新，卫生纸和垃圾袋已标记为补货"); } else if (action === "chore") { setDone((state) => ({ ...state, chore: !state.chore })); notify(done.chore ? "已恢复为待处理" : "值日已完成，辛苦了！"); } else if (action === "rule") { setDone((state) => ({ ...state, rule: true })); notify("已记录你确认过这条公约"); } else if (action === "expense") setExpenseForm(true); }; const openModule = (id) => editMode ? setSelectedId(id) : setActiveModule(id); const enterEdit = () => { setEditMode(true); setSelectedId(null); notify("编辑模式已开启：拖动板块，或从底部素材库添加装饰"); }; const exitEdit = () => { setEditMode(false); setSelectedId(null); notify("公告板布局已保存"); }; const resetLayout = () => { setLayout(initialLayout); setSelectedId(null); notify("已恢复参考图的默认排布"); }; const addDecor = ({ name, asset }) => { const id = `${name}-${Date.now()}`; setLayout((items) => [...items, { id, x: 43 + ((items.length * 7) % 18), y: 28 + ((items.length * 5) % 24), w: 7, h: 7, r: items.length % 2 ? -8 : 7, asset, kind: "decor" }]); setSelectedId(id); notify("素材已贴到公告板，可以继续拖动"); }; const addPhoto = (photo) => { const id = `photo-${photo.id}-${Date.now()}`; setLayout((items) => [...items, { id, x: 42, y: 19, w: 13, h: 16, r: -4, asset: photo.src, photoLabel: photo.label, photo: true, kind: "decor" }]); setSelectedId(id); notify(`已添加拍立得：${photo.label}`); }; const pickPhoto = (photo) => { if (!selectedItem) { addPhoto(photo); return; } if (selectedItem.id === "photo-left" || selectedItem.id === "photo-right") { updateItem(selectedItem.id, { photoAsset: photo.src, photoLabel: photo.label }); notify("这张拍立得已替换为新照片"); return; } if (selectedItem.photo) { updateItem(selectedItem.id, { asset: photo.src, photoLabel: photo.label }); notify("这张拍立得已替换为新照片"); return; } notify("请先选中一张拍立得，再选择照片"); }; const setFastener = (type) => { if (!selectedItem || !fastenerTargets.has(selectedItem.id)) { notify("请先选中一张纸片或黄色待办，再更换固定方式"); return; } updateItem(selectedItem.id, { fastener: type }); notify("固定方式已更换"); }; const deleteSelected = () => { if (!selectedItem || selectedItem.kind !== "decor") return; setLayout((items) => items.filter((item) => item.id !== selectedItem.id)); setSelectedId(null); notify("装饰已移除"); }; const saveExpense = (expense) => { setExpenses((items) => [...items, expense]); setExpenseForm(false); notify(`已记录 ${expense.name} · ¥${expense.amount}`); }; const quickAction = (action) => { if (action === "expense") setExpenseForm(true); else setActiveModule(action === "chore" ? "chores" : action === "stock" ? "supplies" : "rules"); };
  return <div className={`app-shell ${editMode ? "editing" : ""}`}><div className="top-rail"><span className="rail-dot" /><span>ROOMIE / 梧桐公寓共享板</span><span className="rail-note">{editMode ? "正在编辑公告板" : "共享公告板"}</span></div><main className="page-wrap"><section className="board-stage" ref={boardRef} aria-label="Roomie 公寓公告板"><div className="cork-surface" style={{ backgroundImage: `url("${ASSET(CORE, "board-cork-tile.png")}")` }} /><div className="board-content">
    <DraggableItem item={getItem("header")} editMode={editMode} selected={editMode && selectedId === "header"} boardRef={boardRef} onSelect={setSelectedId} onMove={updateItem} onClick={() => editMode && setSelectedId("header")}><HeaderNote /></DraggableItem>
    <DraggableItem item={getItem("photo-left")} editMode={editMode} selected={editMode && selectedId === "photo-left"} boardRef={boardRef} onSelect={setSelectedId} onMove={updateItem} onClick={() => editMode ? setSelectedId("photo-left") : setPhotoViewerId("photo-left")}><Polaroid photo={photoForItem(getItem("photo-left"), photos[0])} editing={editMode} /></DraggableItem>
    <DraggableItem item={getItem("photo-right")} editMode={editMode} selected={editMode && selectedId === "photo-right"} boardRef={boardRef} onSelect={setSelectedId} onMove={updateItem} onClick={() => editMode ? setSelectedId("photo-right") : setPhotoViewerId("photo-right")}><Polaroid photo={photoForItem(getItem("photo-right"), photos[1])} editing={editMode} /></DraggableItem>
    {["aa", "today", "chores", "supplies", "rules"].map((id) => <DraggableItem key={id} item={getItem(id)} editMode={editMode} selected={editMode && selectedId === id} boardRef={boardRef} onSelect={setSelectedId} onMove={updateItem} onClick={() => openModule(id)}>{id === "today" ? <TodayNote done={{ ...done, stock: stockReady }} /> : <ModulePaper moduleId={id} stockReady={stockReady} />}</DraggableItem>)}
    <DraggableItem item={getItem("quick")} editMode={editMode} selected={editMode && selectedId === "quick"} boardRef={boardRef} onSelect={setSelectedId} onMove={updateItem} onClick={() => editMode && setSelectedId("quick")}><QuickActions onAction={quickAction} /></DraggableItem>
    {layout.filter((item) => item.kind === "decor").map((item) => <DraggableItem key={item.id} item={item} layer="decor" editMode={editMode} selected={editMode && selectedId === item.id} boardRef={boardRef} onSelect={setSelectedId} onMove={updateItem} onClick={() => editMode ? setSelectedId(item.id) : item.photo && setPhotoViewerId(item.id)}>{item.photo ? <Polaroid photo={{ src: item.asset, label: item.photoLabel || "拍立得" }} editing={editMode} /> : <img className="decor-image" src={item.asset} alt="" />}</DraggableItem>)}
    {layout.filter((item) => fastenerTargets.has(item.id)).map((item) => <FastenerOverlay key={`fastener-${item.id}`} item={item} />)}
    <DraggableItem item={getItem("keys")} layer="keys" editMode={false} selected={false} boardRef={boardRef} onSelect={setSelectedId} onMove={updateItem}><KeyChain frontKey={frontKey} onKeyFront={(id) => { setFrontKey(id); notify("钥匙已放到最上面"); }} /></DraggableItem>
  </div><img className="wood-frame" src={ASSET(CORE, "board-wood-frame 1.png")} alt="" /><div className="board-edition-button"><button onClick={() => editMode ? exitEdit() : enterEdit()}>{editMode ? "完成编辑" : "编辑公告板"}</button></div></section>{editMode && <MaterialTray selectedItem={selectedItem} onAdd={addDecor} onFastener={setFastener} onPhotoPick={pickPhoto} onDelete={deleteSelected} onClose={exitEdit} onReset={resetLayout} />}</main><footer className="footer-note"><span>在同一块板上，把费用、家务和生活碎片放在一起。</span><span>数据保存在当前浏览器</span></footer>{toast && <div className="toast" role="status">{toast}</div>}<PhotoViewer items={boardPolaroids} activeId={photoViewerId} onClose={() => setPhotoViewerId(null)} onSelect={setPhotoViewerId} /><Modal moduleId={activeModule} onClose={() => setActiveModule(null)} onAction={(action) => { if (action === "expense") { setActiveModule(null); setExpenseForm(true); } else { completeTask(action); setActiveModule(null); } }} expenses={expenses} />{expenseForm && <ExpenseForm onSubmit={saveExpense} onCancel={() => setExpenseForm(false)} />}</div>;
}
